teamkatalogen_historikk:
  target: service_account
  outputs:
    service_account:
      threads: 1
      job_retries: 1
      type: bigquery
      priority: interactive
      location: europe-north1
      dataset: teamkatalogen_historikk
      job_execution_timeout_seconds: 300
      project: pensjon-saksbehandli-prod-1f83

      # method: service-account
      # keyfile: secrets/keyfile.json

      method: service-account-json
      # # prøver om disse kan leses fra env-var, fordi det er mulig i Airflow
      keyfile_json:
        type: "{{ env_var('DBT_ENV_SECRET_type') }}"
        project_id: "{{ env_var('DBT_ENV_SECRET_project_id') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_private_key_id') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_private_key') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_client_email') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_client_id') }}"
        auth_uri: "{{ env_var('DBT_ENV_SECRET_auth_uri') }}"
        token_uri: "{{ env_var('DBT_ENV_SECRET_token_uri') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_auth_provider_x509_cert_url') }}"
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_client_x509_cert_url') }}"
