teamkatalogen_historikk:
  target: "{{ env_var('DBT_AUTHENTICATION', 'oauth') }}" # default er oauth (lokalt)
  outputs:
  # kjøring med service account, som brukes i Airflow
  # DBT_AUTHENTICATION settes til 'service_account' i dbt_run_airflow.py
    service_account:
      threads: 1
      job_retries: 1
      type: bigquery
      priority: interactive
      location: europe-north1
      dataset: teamkatalogen_historikk
      job_execution_timeout_seconds: 300
      project: pensjon-saksbehandli-prod-1f83
      method: service-account-json
      # env_var DBT_ENV_SECRET_* settes fra GSM med dbt_run_airflow.py
      keyfile_json:
        type: "{{ env_var('DBT_ENV_SECRET_type') }}"
        project_id: "{{ env_var('DBT_ENV_SECRET_project_id') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_private_key_id') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_private_key') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_client_email') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_client_id') }}"
        auth_uri: "{{ env_var('DBT_ENV_SECRET_auth_uri') }}"
        token_uri: "{{ env_var('DBT_ENV_SECRET_token_uri') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_auth_provider_x509_cert_url') }}"
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_client_x509_cert_url') }}"

  # dette funker hvis keyfile.json er lastet ned (lokalt eller i Airflow)
    service_account_json_download:
      method: service-account
      keyfile: secrets/keyfile.json
      project: pensjon-saksbehandli-prod-1f83
      dataset: teamkatalogen_historikk

  # kjøring med oauth, som brukes lokalt
    oauth:
      type: bigquery
      method: oauth
      project: pensjon-saksbehandli-prod-1f83
      dataset: teamkatalogen_historikk
      threads: 1